### ISSUE TITLE
Bug: TestAssociation : could not find function "vectorized_wilcoxon"

### ISSUE THREAD

**Issue by lparsons** [dgrtwo/GSEAMA#2]
I believe [this line](https://github.com/dgrtwo/GSEAMA/blob/0477d1adfd7f9b9a40e8a9a1705c4512fe59b38f/R/TestAssociation.R#L61) should use `vectorized_wilcoxon_test` instead (possibly renamed function?)

**Comment by dgrtwo** [comment]
Thank you, fixed!
