### ISSUE TITLE
I can‘t install the GSEAMA in R

### ISSUE THREAD

**Issue by shijianasdf** [dgrtwo/GSEAMA#4]
I can‘t install the GSEAMA in R
After input command "devtools::install_github("dgrtwo/GSEAMA")"
Return Error: C:/Users/lenovo/AppData/Local/Temp/RtmpGa3J5C/R.INSTALL2b342e961cfe/GSEAMA/man/PlotNetwork.Rd:11: Bad \link text

**Comment by shackett** [comment]
I tried installing w/ R 3.5.1 and didn't run into any problems
